@api = http://localhost:4000/kiosko/api/v1/marca
# @api = http://192.168.27.141:9091
#@api = http://192.168.27.141:4000/micliente/api/v3
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InhhdmllciIsImFjdGl2byI6dHJ1ZSwiaWF0IjoxNjg0MTMxNDk3LCJleHAiOjE2ODQxNzQ2OTd9.xLkvNDLkrTOTK1bFxyT-QkE1d7siFgq-kL_MaFIUNwI

### Login
POST http://localhost:4000/kiosko/api/v1/login
Content-Type: application/json

{
    "username":"xavier",
    "password":"123456"
}

### test
GET {{api}}/test
Content-Type: application/json
Authorization: Bearer {{token}}

### list
GET {{api}}/list/0/10
Content-Type: application/json
Authorization: Bearer {{token}}


### list
GET {{api}}/list/xaviercode
Content-Type: application/json
Authorization: Bearer {{token}}


### Create
POST {{api}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre":"Coca Cola",
    "tipo":"Refresco"
}

### Edit
PUT {{api}}/rol/edit/635ca32b86063e346860dad4
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "codigo":"ADM",
    "descripcion":"Administrador",
    "jerarquia":2
}


### Delete
DELETE {{api}}/rol/delete/635f198b94b69c5e1cb75c40
Content-Type: application/json
Authorization: Bearer {{token}}
