version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-hotel
    environment:
      MYSQL_DATABASE: hotel
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./api-hotel
      dockerfile: ../Dockerfile.backend
    container_name: api-hotel
    environment:
      MYSQLDB: hotel
      MYSQLDB_HOST: mysql
      MYSQLDB_PORT: 3306
      MYSQLDB_USR: root
      MYSQLDB_PSW: ''
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./hotel
      dockerfile: ../Dockerfile.frontend
    container_name: hotel-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
